//
// August 13 2026
// Copilot creatin a mockup status reporting system
//

syntax = "proto3";
package sandbox;

import  "google/protobuf/empty.proto";
option go_package = "coptest/proto";


// '0' in enum is special ([ktg] 260828)
enum MyStatus {
     NASTAT    = 0;
     IMOK      = 1;
     NOTOK     = 2;
}

message Status {
        MyStatus State = 1;
}


enum MyEmergency {
     NAEMG   = 0;
     FIRE    = 1;
     EVAC    = 2;
     ALLOK   = 3;
}

message Emergency {
        MyEmergency Wassup = 1;
}


service Async {
         rpc StatusUpdate(stream Status) returns (google.protobuf.Empty);
         rpc EmergencyUpdate(stream Emergency) returns (google.protobuf.Empty);
}

message Onway {
        int32  Code = 1; 
        string Message = 2;
}

message Journey {
        string Plan = 1;
}

service Calls {
         rpc Send(stream Journey) returns (stream Onway);
}
