//
// August 13 2026
// Copilot creatin a mockup status reporting system
//

syntax = "proto3";
package sandbox;

import  "google/protobuf/empty.proto";
option go_package = "coptest/proto";


// '0' in enum is special ([ktg] 260828)
enum MyStatus {
     NASTAT    = 0;
     IMOK      = 1;
     NOTOK     = 2;
}

message Status {
        MyStatus State = 1;
}


enum MyEmergency {
     NAEMG   = 0;
     FIRE    = 1;
     EVAC    = 2;
     ALLOK   = 3;
}

message Emergency {
        MyEmergency Wassup = 1;
}


// Actor/client streams to the User/server
service Async {
         rpc StatusUpdate(stream Status) returns (google.protobuf.Empty);
         rpc EmergencyUpdate(stream Emergency) returns (google.protobuf.Empty);
}

message StatusQuery {
        string Squery = 1;
}

message StatusResponse {
        string Sresponse = 1;
}

// Actor/client serves responsens to User/server's queries
service Calls {
         rpc Send(stream StatusQuery) returns (stream StatusResponse);
}
