//
// August 13 2026
// Copilot creatin a mockup status reporting system
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pilot.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// /////////////////////////////////////////////////////////////
// ASYNC
//
// '0' in enum is special ([ktg] 260828)
type MyStatus int32

const (
	MyStatus_NASTAT MyStatus = 0
	MyStatus_IMOK   MyStatus = 1
	MyStatus_NOTOK  MyStatus = 2
)

// Enum value maps for MyStatus.
var (
	MyStatus_name = map[int32]string{
		0: "NASTAT",
		1: "IMOK",
		2: "NOTOK",
	}
	MyStatus_value = map[string]int32{
		"NASTAT": 0,
		"IMOK":   1,
		"NOTOK":  2,
	}
)

func (x MyStatus) Enum() *MyStatus {
	p := new(MyStatus)
	*p = x
	return p
}

func (x MyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_proto_enumTypes[0].Descriptor()
}

func (MyStatus) Type() protoreflect.EnumType {
	return &file_pilot_proto_enumTypes[0]
}

func (x MyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MyStatus.Descriptor instead.
func (MyStatus) EnumDescriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{0}
}

type MyEmergency int32

const (
	MyEmergency_NA    MyEmergency = 0
	MyEmergency_STOP  MyEmergency = 1
	MyEmergency_ALLOK MyEmergency = 2
)

// Enum value maps for MyEmergency.
var (
	MyEmergency_name = map[int32]string{
		0: "NA",
		1: "STOP",
		2: "ALLOK",
	}
	MyEmergency_value = map[string]int32{
		"NA":    0,
		"STOP":  1,
		"ALLOK": 2,
	}
)

func (x MyEmergency) Enum() *MyEmergency {
	p := new(MyEmergency)
	*p = x
	return p
}

func (x MyEmergency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MyEmergency) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_proto_enumTypes[1].Descriptor()
}

func (MyEmergency) Type() protoreflect.EnumType {
	return &file_pilot_proto_enumTypes[1]
}

func (x MyEmergency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MyEmergency.Descriptor instead.
func (MyEmergency) EnumDescriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{1}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Motion        string                 `protobuf:"bytes,1,opt,name=Motion,proto3" json:"Motion,omitempty"`
	Speed         int32                  `protobuf:"varint,2,opt,name=Speed,proto3" json:"Speed,omitempty"`
	Spot          int32                  `protobuf:"varint,3,opt,name=Spot,proto3" json:"Spot,omitempty"`
	Target        int32                  `protobuf:"varint,4,opt,name=Target,proto3" json:"Target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_pilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetMotion() string {
	if x != nil {
		return x.Motion
	}
	return ""
}

func (x *Status) GetSpeed() int32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Status) GetSpot() int32 {
	if x != nil {
		return x.Spot
	}
	return 0
}

func (x *Status) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

type Emergency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wassup        MyEmergency            `protobuf:"varint,1,opt,name=Wassup,proto3,enum=sandbox.MyEmergency" json:"Wassup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emergency) Reset() {
	*x = Emergency{}
	mi := &file_pilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emergency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emergency) ProtoMessage() {}

func (x *Emergency) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emergency.ProtoReflect.Descriptor instead.
func (*Emergency) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{1}
}

func (x *Emergency) GetWassup() MyEmergency {
	if x != nil {
		return x.Wassup
	}
	return MyEmergency_NA
}

// /////////////////////////////////////////////////////////////
// CALLS
type StateQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Squery        string                 `protobuf:"bytes,1,opt,name=Squery,proto3" json:"Squery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateQuery) Reset() {
	*x = StateQuery{}
	mi := &file_pilot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateQuery) ProtoMessage() {}

func (x *StateQuery) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateQuery.ProtoReflect.Descriptor instead.
func (*StateQuery) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{2}
}

func (x *StateQuery) GetSquery() string {
	if x != nil {
		return x.Squery
	}
	return ""
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sresponse     string                 `protobuf:"bytes,1,opt,name=Sresponse,proto3" json:"Sresponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_pilot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{3}
}

func (x *StateResponse) GetSresponse() string {
	if x != nil {
		return x.Sresponse
	}
	return ""
}

type TargetCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        int32                  `protobuf:"varint,1,opt,name=Target,proto3" json:"Target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetCommand) Reset() {
	*x = TargetCommand{}
	mi := &file_pilot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetCommand) ProtoMessage() {}

func (x *TargetCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetCommand.ProtoReflect.Descriptor instead.
func (*TargetCommand) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{4}
}

func (x *TargetCommand) GetTarget() int32 {
	if x != nil {
		return x.Target
	}
	return 0
}

type TargetReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetReport) Reset() {
	*x = TargetReport{}
	mi := &file_pilot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetReport) ProtoMessage() {}

func (x *TargetReport) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetReport.ProtoReflect.Descriptor instead.
func (*TargetReport) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{5}
}

func (x *TargetReport) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TargetReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pilot_proto protoreflect.FileDescriptor

const file_pilot_proto_rawDesc = "" +
	"\n" +
	"\vpilot.proto\x12\asandbox\x1a\x1bgoogle/protobuf/empty.proto\"b\n" +
	"\x06Status\x12\x16\n" +
	"\x06Motion\x18\x01 \x01(\tR\x06Motion\x12\x14\n" +
	"\x05Speed\x18\x02 \x01(\x05R\x05Speed\x12\x12\n" +
	"\x04Spot\x18\x03 \x01(\x05R\x04Spot\x12\x16\n" +
	"\x06Target\x18\x04 \x01(\x05R\x06Target\"9\n" +
	"\tEmergency\x12,\n" +
	"\x06Wassup\x18\x01 \x01(\x0e2\x14.sandbox.MyEmergencyR\x06Wassup\"$\n" +
	"\n" +
	"StateQuery\x12\x16\n" +
	"\x06Squery\x18\x01 \x01(\tR\x06Squery\"-\n" +
	"\rStateResponse\x12\x1c\n" +
	"\tSresponse\x18\x01 \x01(\tR\tSresponse\"'\n" +
	"\rTargetCommand\x12\x16\n" +
	"\x06Target\x18\x01 \x01(\x05R\x06Target\"<\n" +
	"\fTargetReport\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x05R\x04Code\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage*+\n" +
	"\bMyStatus\x12\n" +
	"\n" +
	"\x06NASTAT\x10\x00\x12\b\n" +
	"\x04IMOK\x10\x01\x12\t\n" +
	"\x05NOTOK\x10\x02**\n" +
	"\vMyEmergency\x12\x06\n" +
	"\x02NA\x10\x00\x12\b\n" +
	"\x04STOP\x10\x01\x12\t\n" +
	"\x05ALLOK\x10\x022\x83\x01\n" +
	"\x05Async\x129\n" +
	"\fStatusUpdate\x12\x0f.sandbox.Status\x1a\x16.google.protobuf.Empty(\x01\x12?\n" +
	"\x0fEmergencyUpdate\x12\x12.sandbox.Emergency\x1a\x16.google.protobuf.Empty(\x012w\n" +
	"\x05Calls\x123\n" +
	"\x04Send\x12\x13.sandbox.StateQuery\x1a\x16.sandbox.StateResponse\x129\n" +
	"\x06MoveTo\x12\x16.sandbox.TargetCommand\x1a\x15.sandbox.TargetReport0\x01B\x0fZ\rcoptest/protob\x06proto3"

var (
	file_pilot_proto_rawDescOnce sync.Once
	file_pilot_proto_rawDescData []byte
)

func file_pilot_proto_rawDescGZIP() []byte {
	file_pilot_proto_rawDescOnce.Do(func() {
		file_pilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilot_proto_rawDesc), len(file_pilot_proto_rawDesc)))
	})
	return file_pilot_proto_rawDescData
}

var file_pilot_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pilot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pilot_proto_goTypes = []any{
	(MyStatus)(0),         // 0: sandbox.MyStatus
	(MyEmergency)(0),      // 1: sandbox.MyEmergency
	(*Status)(nil),        // 2: sandbox.Status
	(*Emergency)(nil),     // 3: sandbox.Emergency
	(*StateQuery)(nil),    // 4: sandbox.StateQuery
	(*StateResponse)(nil), // 5: sandbox.StateResponse
	(*TargetCommand)(nil), // 6: sandbox.TargetCommand
	(*TargetReport)(nil),  // 7: sandbox.TargetReport
	(*empty.Empty)(nil),   // 8: google.protobuf.Empty
}
var file_pilot_proto_depIdxs = []int32{
	1, // 0: sandbox.Emergency.Wassup:type_name -> sandbox.MyEmergency
	2, // 1: sandbox.Async.StatusUpdate:input_type -> sandbox.Status
	3, // 2: sandbox.Async.EmergencyUpdate:input_type -> sandbox.Emergency
	4, // 3: sandbox.Calls.Send:input_type -> sandbox.StateQuery
	6, // 4: sandbox.Calls.MoveTo:input_type -> sandbox.TargetCommand
	8, // 5: sandbox.Async.StatusUpdate:output_type -> google.protobuf.Empty
	8, // 6: sandbox.Async.EmergencyUpdate:output_type -> google.protobuf.Empty
	5, // 7: sandbox.Calls.Send:output_type -> sandbox.StateResponse
	7, // 8: sandbox.Calls.MoveTo:output_type -> sandbox.TargetReport
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pilot_proto_init() }
func file_pilot_proto_init() {
	if File_pilot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilot_proto_rawDesc), len(file_pilot_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pilot_proto_goTypes,
		DependencyIndexes: file_pilot_proto_depIdxs,
		EnumInfos:         file_pilot_proto_enumTypes,
		MessageInfos:      file_pilot_proto_msgTypes,
	}.Build()
	File_pilot_proto = out.File
	file_pilot_proto_goTypes = nil
	file_pilot_proto_depIdxs = nil
}
