//
// August 13 2026
// Copilot creatin a mockup status reporting system
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: pilot.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Async_StatusUpdate_FullMethodName    = "/sandbox.Async/StatusUpdate"
	Async_EmergencyUpdate_FullMethodName = "/sandbox.Async/EmergencyUpdate"
)

// AsyncClient is the client API for Async service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Actor/client streams to the User/server
type AsyncClient interface {
	StatusUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Status, empty.Empty], error)
	EmergencyUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Emergency, empty.Empty], error)
}

type asyncClient struct {
	cc grpc.ClientConnInterface
}

func NewAsyncClient(cc grpc.ClientConnInterface) AsyncClient {
	return &asyncClient{cc}
}

func (c *asyncClient) StatusUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Status, empty.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Async_ServiceDesc.Streams[0], Async_StatusUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Status, empty.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Async_StatusUpdateClient = grpc.ClientStreamingClient[Status, empty.Empty]

func (c *asyncClient) EmergencyUpdate(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Emergency, empty.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Async_ServiceDesc.Streams[1], Async_EmergencyUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Emergency, empty.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Async_EmergencyUpdateClient = grpc.ClientStreamingClient[Emergency, empty.Empty]

// AsyncServer is the server API for Async service.
// All implementations must embed UnimplementedAsyncServer
// for forward compatibility.
//
// Actor/client streams to the User/server
type AsyncServer interface {
	StatusUpdate(grpc.ClientStreamingServer[Status, empty.Empty]) error
	EmergencyUpdate(grpc.ClientStreamingServer[Emergency, empty.Empty]) error
	mustEmbedUnimplementedAsyncServer()
}

// UnimplementedAsyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsyncServer struct{}

func (UnimplementedAsyncServer) StatusUpdate(grpc.ClientStreamingServer[Status, empty.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method StatusUpdate not implemented")
}
func (UnimplementedAsyncServer) EmergencyUpdate(grpc.ClientStreamingServer[Emergency, empty.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method EmergencyUpdate not implemented")
}
func (UnimplementedAsyncServer) mustEmbedUnimplementedAsyncServer() {}
func (UnimplementedAsyncServer) testEmbeddedByValue()               {}

// UnsafeAsyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsyncServer will
// result in compilation errors.
type UnsafeAsyncServer interface {
	mustEmbedUnimplementedAsyncServer()
}

func RegisterAsyncServer(s grpc.ServiceRegistrar, srv AsyncServer) {
	// If the following call pancis, it indicates UnimplementedAsyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Async_ServiceDesc, srv)
}

func _Async_StatusUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AsyncServer).StatusUpdate(&grpc.GenericServerStream[Status, empty.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Async_StatusUpdateServer = grpc.ClientStreamingServer[Status, empty.Empty]

func _Async_EmergencyUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AsyncServer).EmergencyUpdate(&grpc.GenericServerStream[Emergency, empty.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Async_EmergencyUpdateServer = grpc.ClientStreamingServer[Emergency, empty.Empty]

// Async_ServiceDesc is the grpc.ServiceDesc for Async service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Async_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.Async",
	HandlerType: (*AsyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusUpdate",
			Handler:       _Async_StatusUpdate_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "EmergencyUpdate",
			Handler:       _Async_EmergencyUpdate_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pilot.proto",
}

const (
	Calls_Send_FullMethodName   = "/sandbox.Calls/Send"
	Calls_MoveTo_FullMethodName = "/sandbox.Calls/MoveTo"
)

// CallsClient is the client API for Calls service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Actor/client serves responsens to User/server's queries
type CallsClient interface {
	Send(ctx context.Context, in *StateQuery, opts ...grpc.CallOption) (*StateResponse, error)
	MoveTo(ctx context.Context, in *TargetCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TargetReport], error)
}

type callsClient struct {
	cc grpc.ClientConnInterface
}

func NewCallsClient(cc grpc.ClientConnInterface) CallsClient {
	return &callsClient{cc}
}

func (c *callsClient) Send(ctx context.Context, in *StateQuery, opts ...grpc.CallOption) (*StateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateResponse)
	err := c.cc.Invoke(ctx, Calls_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *callsClient) MoveTo(ctx context.Context, in *TargetCommand, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TargetReport], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Calls_ServiceDesc.Streams[0], Calls_MoveTo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TargetCommand, TargetReport]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calls_MoveToClient = grpc.ServerStreamingClient[TargetReport]

// CallsServer is the server API for Calls service.
// All implementations must embed UnimplementedCallsServer
// for forward compatibility.
//
// Actor/client serves responsens to User/server's queries
type CallsServer interface {
	Send(context.Context, *StateQuery) (*StateResponse, error)
	MoveTo(*TargetCommand, grpc.ServerStreamingServer[TargetReport]) error
	mustEmbedUnimplementedCallsServer()
}

// UnimplementedCallsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallsServer struct{}

func (UnimplementedCallsServer) Send(context.Context, *StateQuery) (*StateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedCallsServer) MoveTo(*TargetCommand, grpc.ServerStreamingServer[TargetReport]) error {
	return status.Errorf(codes.Unimplemented, "method MoveTo not implemented")
}
func (UnimplementedCallsServer) mustEmbedUnimplementedCallsServer() {}
func (UnimplementedCallsServer) testEmbeddedByValue()               {}

// UnsafeCallsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallsServer will
// result in compilation errors.
type UnsafeCallsServer interface {
	mustEmbedUnimplementedCallsServer()
}

func RegisterCallsServer(s grpc.ServiceRegistrar, srv CallsServer) {
	// If the following call pancis, it indicates UnimplementedCallsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Calls_ServiceDesc, srv)
}

func _Calls_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallsServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Calls_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallsServer).Send(ctx, req.(*StateQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calls_MoveTo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TargetCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CallsServer).MoveTo(m, &grpc.GenericServerStream[TargetCommand, TargetReport]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Calls_MoveToServer = grpc.ServerStreamingServer[TargetReport]

// Calls_ServiceDesc is the grpc.ServiceDesc for Calls service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Calls_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.Calls",
	HandlerType: (*CallsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Calls_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MoveTo",
			Handler:       _Calls_MoveTo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pilot.proto",
}
