//
// August 13 2026
// Copilot creatin a mockup status reporting system
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pilot.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MyStatus int32

const (
	MyStatus_IMOK  MyStatus = 0
	MyStatus_NOTOK MyStatus = 1
)

// Enum value maps for MyStatus.
var (
	MyStatus_name = map[int32]string{
		0: "IMOK",
		1: "NOTOK",
	}
	MyStatus_value = map[string]int32{
		"IMOK":  0,
		"NOTOK": 1,
	}
)

func (x MyStatus) Enum() *MyStatus {
	p := new(MyStatus)
	*p = x
	return p
}

func (x MyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_proto_enumTypes[0].Descriptor()
}

func (MyStatus) Type() protoreflect.EnumType {
	return &file_pilot_proto_enumTypes[0]
}

func (x MyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MyStatus.Descriptor instead.
func (MyStatus) EnumDescriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{0}
}

type MyEmergency int32

const (
	MyEmergency_FIRE  MyEmergency = 0
	MyEmergency_EVAC  MyEmergency = 1
	MyEmergency_ALLOK MyEmergency = 2
)

// Enum value maps for MyEmergency.
var (
	MyEmergency_name = map[int32]string{
		0: "FIRE",
		1: "EVAC",
		2: "ALLOK",
	}
	MyEmergency_value = map[string]int32{
		"FIRE":  0,
		"EVAC":  1,
		"ALLOK": 2,
	}
)

func (x MyEmergency) Enum() *MyEmergency {
	p := new(MyEmergency)
	*p = x
	return p
}

func (x MyEmergency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MyEmergency) Descriptor() protoreflect.EnumDescriptor {
	return file_pilot_proto_enumTypes[1].Descriptor()
}

func (MyEmergency) Type() protoreflect.EnumType {
	return &file_pilot_proto_enumTypes[1]
}

func (x MyEmergency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MyEmergency.Descriptor instead.
func (MyEmergency) EnumDescriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{1}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         MyStatus               `protobuf:"varint,1,opt,name=State,proto3,enum=sandbox.MyStatus" json:"State,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_pilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetState() MyStatus {
	if x != nil {
		return x.State
	}
	return MyStatus_IMOK
}

type Emergency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wassup        MyEmergency            `protobuf:"varint,1,opt,name=Wassup,proto3,enum=sandbox.MyEmergency" json:"Wassup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emergency) Reset() {
	*x = Emergency{}
	mi := &file_pilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emergency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emergency) ProtoMessage() {}

func (x *Emergency) ProtoReflect() protoreflect.Message {
	mi := &file_pilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emergency.ProtoReflect.Descriptor instead.
func (*Emergency) Descriptor() ([]byte, []int) {
	return file_pilot_proto_rawDescGZIP(), []int{1}
}

func (x *Emergency) GetWassup() MyEmergency {
	if x != nil {
		return x.Wassup
	}
	return MyEmergency_FIRE
}

var File_pilot_proto protoreflect.FileDescriptor

const file_pilot_proto_rawDesc = "" +
	"\n" +
	"\vpilot.proto\x12\asandbox\x1a\x1bgoogle/protobuf/empty.proto\"1\n" +
	"\x06Status\x12'\n" +
	"\x05State\x18\x01 \x01(\x0e2\x11.sandbox.MyStatusR\x05State\"9\n" +
	"\tEmergency\x12,\n" +
	"\x06Wassup\x18\x01 \x01(\x0e2\x14.sandbox.MyEmergencyR\x06Wassup*\x1f\n" +
	"\bMyStatus\x12\b\n" +
	"\x04IMOK\x10\x00\x12\t\n" +
	"\x05NOTOK\x10\x01*,\n" +
	"\vMyEmergency\x12\b\n" +
	"\x04FIRE\x10\x00\x12\b\n" +
	"\x04EVAC\x10\x01\x12\t\n" +
	"\x05ALLOK\x10\x022\x80\x01\n" +
	"\x05Async\x129\n" +
	"\fStatusUpdate\x12\x0f.sandbox.Status\x1a\x16.google.protobuf.Empty(\x01\x12<\n" +
	"\x0fEmergencyUpdate\x12\x0f.sandbox.Status\x1a\x16.google.protobuf.Empty(\x01B\x0fZ\rcoptest/protob\x06proto3"

var (
	file_pilot_proto_rawDescOnce sync.Once
	file_pilot_proto_rawDescData []byte
)

func file_pilot_proto_rawDescGZIP() []byte {
	file_pilot_proto_rawDescOnce.Do(func() {
		file_pilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pilot_proto_rawDesc), len(file_pilot_proto_rawDesc)))
	})
	return file_pilot_proto_rawDescData
}

var file_pilot_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pilot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pilot_proto_goTypes = []any{
	(MyStatus)(0),       // 0: sandbox.MyStatus
	(MyEmergency)(0),    // 1: sandbox.MyEmergency
	(*Status)(nil),      // 2: sandbox.Status
	(*Emergency)(nil),   // 3: sandbox.Emergency
	(*empty.Empty)(nil), // 4: google.protobuf.Empty
}
var file_pilot_proto_depIdxs = []int32{
	0, // 0: sandbox.Status.State:type_name -> sandbox.MyStatus
	1, // 1: sandbox.Emergency.Wassup:type_name -> sandbox.MyEmergency
	2, // 2: sandbox.Async.StatusUpdate:input_type -> sandbox.Status
	2, // 3: sandbox.Async.EmergencyUpdate:input_type -> sandbox.Status
	4, // 4: sandbox.Async.StatusUpdate:output_type -> google.protobuf.Empty
	4, // 5: sandbox.Async.EmergencyUpdate:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pilot_proto_init() }
func file_pilot_proto_init() {
	if File_pilot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pilot_proto_rawDesc), len(file_pilot_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pilot_proto_goTypes,
		DependencyIndexes: file_pilot_proto_depIdxs,
		EnumInfos:         file_pilot_proto_enumTypes,
		MessageInfos:      file_pilot_proto_msgTypes,
	}.Build()
	File_pilot_proto = out.File
	file_pilot_proto_goTypes = nil
	file_pilot_proto_depIdxs = nil
}
