//
// August 13 2026
// Copilot creatin a mockup status reporting system
//

syntax = "proto3";
package sandbox;

import  "google/protobuf/empty.proto";
option go_package = "coptest/proto";



///////////////////////////////////////////////////////////////
// ASYNC
//
// '0' in enum is special ([ktg] 260828)
enum MyStatus {
     NASTAT    = 0;
     IMOK      = 1;
     NOTOK     = 2;
}

message Status {
        string Motion = 1;
        int32 Speed = 2;
        int32 Spot = 3;
        int32 Target = 4;
}


enum MyEmergency {
     NA      = 0;
     STOP    = 1;
     ALLOK   = 2;
}

message Emergency {
        MyEmergency Wassup = 1;
}


// Actor/client streams to the User/server
service Async {
         rpc StatusUpdate(stream Status) returns (google.protobuf.Empty);
         rpc EmergencyUpdate(stream Emergency) returns (google.protobuf.Empty);
}


///////////////////////////////////////////////////////////////
// CALLS
//
message StateQuery {
        string Squery = 1;
}
message StateResponse {
        string Sresponse = 1;
}

message TargetCommand {
        int32 Target = 1;       
}
message TargetReport {
        int32 Code = 1;
        string Message = 2;
}

// Actor/client serves responsens to User/server's queries
service Calls {
         rpc Send(StateQuery) returns (StateResponse);
         rpc MoveTo(TargetCommand) returns (stream TargetReport);
}
